# Generated by Django 2.0.6 on 2018-06-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DnsOperateLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operate_user', models.CharField(max_length=255, verbose_name='记录名称')),
                ('request_ip', models.GenericIPAddressField(protocol='ipv4', verbose_name='请求ip')),
                ('operate_url', models.URLField(verbose_name='操作url')),
                ('operate_type', models.CharField(choices=[('POST', '增加'), ('DELETE', '删除'), ('GET', '查询'), ('PUT', '修改')], max_length=8, verbose_name='操作类型')),
                ('params', models.TextField(verbose_name='入参')),
                ('status', models.CharField(choices=[(0, '失败'), (1, '成功')], max_length=8, verbose_name='返回状态')),
                ('start_time', models.DateTimeField(verbose_name='调用开始时间')),
                ('end_time', models.DateTimeField(verbose_name='调用结束时间')),
                ('message', models.TextField(verbose_name='异常返回结果')),
                ('result', models.TextField(verbose_name='接口返回结果')),
            ],
        ),
        migrations.CreateModel(
            name='DnsRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='记录名称')),
                ('record_type', models.CharField(max_length=32, verbose_name='记录类型')),
                ('ttl', models.IntegerField(verbose_name='记录缓存生存时间')),
                ('record_value', models.TextField(verbose_name='记录值')),
                ('view_id', models.IntegerField(verbose_name='view id')),
                ('zone_id', models.IntegerField(verbose_name='view id')),
                ('request_time', models.DateTimeField(auto_now_add=True, verbose_name='记录请求时间，如果后面进来的请求时间小于当前，不做处理')),
                ('request_ip', models.GenericIPAddressField(protocol='ipv4', verbose_name='请求IP')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('delete_time', models.DateTimeField(verbose_name='删除时间')),
                ('is_delete', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DnsView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('server', models.CharField(max_length=255, verbose_name='server地址')),
                ('view', models.CharField(max_length=255, verbose_name='view名称')),
                ('keyring', models.CharField(max_length=255, verbose_name='view key')),
                ('zone_id', models.IntegerField(verbose_name='zoneid')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('delete_time', models.DateTimeField(verbose_name='删除时间')),
                ('is_delete', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DnsZone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=255, verbose_name='zone名称')),
                ('serial_num', models.IntegerField(verbose_name='序列号')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('delete_time', models.DateTimeField(verbose_name='删除时间')),
                ('is_delete', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0)),
            ],
        ),
    ]
